##------------------------------------------##
## General configuration
##------------------------------------------##

# CID  (Host setup and management > Sensor downloads)
export FALCON_CID=<CID_WITH_CHECKSUM>

# API Credential (Support and resources > API clients and keys)
export FALCON_CLIENT_ID=<CLIENT ID>
export FALCON_CLIENT_SECRET=<CLIENT_SECRET>


##------------------------------------------##
## Region
##------------------------------------------##

# US-1
# export FALCON_CLOUD_API=api.crowdstrike.com
# export FALCON_REGION=us-1
# export FALCON_CONTAINER_REGISTRY=registry.crowdstrike.com

# US-2
export FALCON_REGION=us-2
export FALCON_CLOUD_API=api.us-2.crowdstrike.com
export FALCON_CONTAINER_REGISTRY=registry.crowdstrike.com


##------------------------------------------##
## Azure configuration
##------------------------------------------##

# Subscription ID
export FALCON_AZR_SUBSCRIPTION_ID=

# Resource Group Name
export FALCON_AZR_RESOURCE_GRP_NAME=

# ACR Login server name
export FALCON_ACR_NAME=<registry-name>.azurecr.io


##------------------------------------------##
## container image configuration
##------------------------------------------##
# Set image name that you want to install falcon container sensor.
export FALCON_SOURCE_IMAGE=<REPOSITORY>:<TAG>

# Set image name that will be created after the falcon container sensor is installed.
export FALCON_TARGET_IMAGE=<REPOSITORY>:<TAG>

# Token file path for ACR access. This file is automatically generated, so there is no need to edit.
export FALCON_ACR_CONFIG_JSON_PATH=./config.json


##------------------------------------------##
## falcon container sensor configuration
##------------------------------------------##
# Platform type. x86_64 or aarch64
export FALCON_PLATFORM_TYPE=x86_64

# Set falcon sensor tags. For multiple tags, use "\,". e.g., "tag1\,tag2\,tag3"
export FALCON_SENSOR_GROUPING_TAGS="tag1"

